force-app/main/default/objects/Premium_Client__c/Premium_Client__c.object-meta.xml
<CustomObject>
    <label>Premium_Client</label>
    <nameField>
        <label>Premium_Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premium_Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premium_Client__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Premium_Clients</relationshipLabel>
    <relationshipName>Premium_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premium_Client__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PremiumTriggerHandlerTest.cls
@IsTest
public class PremiumTriggerHandlerTest {
    @IsTest static void testAfterInsertOrUpdate() {
        Contact c = new Contact(FirstName='Gold', LastName='User');
        insert c;

        Premium_Client__c prem = new Premium_Client__c(Contact__c = c.Id, Level__c = 'Gold');
        insert prem;

        Contact updated = [SELECT VIP__c FROM Contact WHERE Id = :c.Id];
        System.assertEquals(true, updated.VIP__c);
    }
}